config/routes.rb
Rails.application.routes.draw do
	resources :folders do
     	resources :photos
   	end
	root 'folders#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/folder.rb
class Folder < ApplicationRecord
	has_many :photos
end

app/models/photo.rb
class Photo < ApplicationRecord
	 has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	 validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  	 belongs_to :folder
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
	def index
		@folders = Folder.all
	end

	def show
		@folder=Folder.find(params[:id])
	end

	def new
		@folder = Folder.new
	end

	def destroy
		@folder=Folder.find(params[:id])
		@folder.destroy
    	redirect_to root_path
	end

	def create
		@folder=Folder.create(folder_params)
		if @folder.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	private
	def folder_params
		params.require(:folder).permit(:name)
	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @folder = Folder.all
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to root_path
  end

  def create
    @folder = Folder.find(params[:folder_id])
    @photo = @folder.photos.create(params[:photo].permit(:avatar))
    redirect_to folders_path
  end

  private

  def user_params
    params.require(:photo).permit(:avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/folders/index.html.erb
<div class="jumbotron create-folder">
	<center><%= link_to "Create Folder", new_folder_path, class: 'btn btn-success'  %></center>
</div>

<div class="jumbotron">
	<div class="container">
		<% @folders.each do |folder| %>
			<div class="col-md-3 folder-item">
				<i class="fa fa-folder"></i>
				<p><%= folder.name %></p>
				<%= link_to "See Folder", folder_path(folder.id) %><br /><br />
			</div>
		<% end %>
		</div>
	</div>
</div>

app/views/folders/new.html.erb
<h1>New Folder</h1>

<%= form_for :folder, url: folders_path do |f| %>
	<%= f.text_field :name, placeholder: 'Enter name of folder' %>
	<%= f.submit %>
<% end %>

app/views/folders/show.html.erb
<h1>This folder: <%= @folder.name %>
<%= link_to "Delete Folder", folder_path(@folder),method: :delete, class: "btn btn-danger"%>
</h1>
<div class="container">
	<% @folder.photos.each do |photo| %>
		<div class="image-holder">
			<%= image_tag photo.avatar.url, class: 'hi' %><br />
			<div class="url"><p><%= photo.avatar.url %></p></div><br />
			<%= link_to "Delete Photo", [photo.folder, photo], method: :delete, class: 'button', data: {confirm: "Are You Sure?"}  %>
		</div>
	<% end %>
</div>

<%= form_for([@folder, @folder.photos.build]) do |f| %>
	<%= f.file_field :avatar %>
  	<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Robobox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/create.html.erb
<h1>Photos#create</h1>
<p>Find me in app/views/photos/create.html.erb</p>

app/views/photos/destroy.html.erb
<h1>Photos#destroy</h1>
<p>Find me in app/views/photos/destroy.html.erb</p>

app/views/photos/edit.html.erb
<h1>Photos#edit</h1>
<p>Find me in app/views/photos/edit.html.erb</p>

app/views/photos/index.html.erb
<h1>Photos#index</h1>
<p>Find me in app/views/photos/index.html.erb</p>


<% @photo.each do |photo| %>
<%= image_tag photo.avatar.url %><br />

<% end %>

<%= link_to "New", new_photo_path %>

app/views/photos/new.html.erb
<h1>Photos#new</h1>
<p>Find me in app/views/photos/new.html.erb</p>


<%= form_for :photo, url: photos_path, html: { multipart: true } do |form| %>
  <%= form.file_field :avatar %>
  <%= form.submit %>
<% end %>

app/views/photos/update.html.erb
<h1>Photos#update</h1>
<p>Find me in app/views/photos/update.html.erb</p>